FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-test.txt /app/requirements-test.txt
RUN pip install --no-cache-dir --default-timeout=300 --retries=10 -r /app/requirements-test.txt

COPY . /app

CMD ["pytest", "tests/", "-v", "--cov=data_pipeline", "--cov-report=xml"]
